// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALt-ZPMyRn-H1bTF0PyMEbtyqQIhfMDjQ',
    appId: '1:61169296771:web:b6e5a43b7adacd91bd82b6',
    messagingSenderId: '61169296771',
    projectId: 'lottery-16739',
    authDomain: 'lottery-16739.firebaseapp.com',
    databaseURL: 'https://lottery-16739-default-rtdb.firebaseio.com',
    storageBucket: 'lottery-16739.appspot.com',
    measurementId: 'G-FSZK2P0HY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtoJnxlH0EOiRarPa2Y7WNjA8pE374Gs8',
    appId: '1:61169296771:android:52deb748f534b9e9bd82b6',
    messagingSenderId: '61169296771',
    projectId: 'lottery-16739',
    databaseURL: 'https://lottery-16739-default-rtdb.firebaseio.com',
    storageBucket: 'lottery-16739.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDou9ZPmvySCfc32YhQ9NlBfzYbOCv9h2Y',
    appId: '1:61169296771:ios:cd53ffebb07bdc18bd82b6',
    messagingSenderId: '61169296771',
    projectId: 'lottery-16739',
    databaseURL: 'https://lottery-16739-default-rtdb.firebaseio.com',
    storageBucket: 'lottery-16739.appspot.com',
    iosBundleId: 'com.mylott.lottery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDou9ZPmvySCfc32YhQ9NlBfzYbOCv9h2Y',
    appId: '1:61169296771:ios:7b014d70c61e1860bd82b6',
    messagingSenderId: '61169296771',
    projectId: 'lottery-16739',
    databaseURL: 'https://lottery-16739-default-rtdb.firebaseio.com',
    storageBucket: 'lottery-16739.appspot.com',
    iosBundleId: 'com.example.lotteryFlutterApplication.RunnerTests',
  );
}
